import { normalizeMlbAbbrev } from "./mlbLogos";

export const TEAM_ABBREVS: Record<string, string> = {
  "Los Angeles Lakers": "LAL",
  "New York Knicks": "NYK",
  "Boston Celtics": "BOS",
  "Miami Heat": "MIA",
  "Chicago Bulls": "CHI",
  "Golden State Warriors": "GSW",
  "Brooklyn Nets": "BKN",
  "Dallas Mavericks": "DAL",
  "Denver Nuggets": "DEN",
  "Philadelphia 76ers": "PHI",
  "Phoenix Suns": "PHX",
  "Milwaukee Bucks": "MIL",
  "Toronto Raptors": "TOR",
  "Atlanta Hawks": "ATL",
  "Orlando Magic": "ORL",
  "Indiana Pacers": "IND",
  "Cleveland Cavaliers": "CLE",
  "Detroit Pistons": "DET",
  "San Antonio Spurs": "SAS",
  "Houston Rockets": "HOU",
  "Memphis Grizzlies": "MEM",
  "New Orleans Pelicans": "NOP",
  "Oklahoma City Thunder": "OKC",
  "Utah Jazz": "UTA",
  "Sacramento Kings": "SAC",
  "Portland Trail Blazers": "POR",
  "Minnesota Timberwolves": "MIN",
  "LA Clippers": "LAC",
  "Charlotte Hornets": "CHA",
  "Washington Wizards": "WSH",
  "Arizona Cardinals": "ARI",
  "Atlanta Falcons": "ATL",
  "Baltimore Ravens": "BAL",
  "Buffalo Bills": "BUF",
  "Carolina Panthers": "CAR",
  "Chicago Bears": "CHI",
  "Cincinnati Bengals": "CIN",
  "Cleveland Browns": "CLE",
  "Dallas Cowboys": "DAL",
  "Denver Broncos": "DEN",
  "Detroit Lions": "DET",
  "Green Bay Packers": "GB",
  "Houston Texans": "HOU",
  "Indianapolis Colts": "IND",
  "Jacksonville Jaguars": "JAX",
  "Kansas City Chiefs": "KC",
  "Las Vegas Raiders": "LV",
  "Los Angeles Chargers": "LAC",
  "Los Angeles Rams": "LAR",
  "Miami Dolphins": "MIA",
  "Minnesota Vikings": "MIN",
  "New England Patriots": "NE",
  "New Orleans Saints": "NO",
  "New York Giants": "NYG",
  "New York Jets": "NYJ",
  "Philadelphia Eagles": "PHI",
  "Pittsburgh Steelers": "PIT",
  "San Francisco 49ers": "SF",
  "Seattle Seahawks": "SEA",
  "Tampa Bay Buccaneers": "TB",
  "Tennessee Titans": "TEN",
  "Washington Commanders": "WSH",
};

export function getTeamAbbrev(teamName: string) {
  return TEAM_ABBREVS[teamName] ?? normalizeMlbAbbrev(teamName);
}
